version: "3.7"
services:
    python-basico:
        build: 
            dockerfile: ./python.Dockerfile
            context: .
        container_name: python-basico
        volumes:
            - /home/lusa/aulas_python_mestrado/script:/usr/src/myapp
        networks:
            - default
        ports:
            - 8888:8888
            - 8080:8080

volumes:
    persistent:
